name: Build
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual triggering
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: code-check
      run: cargo check
